declare function maybeDeserialize(inputData: any): boolean;
declare function maybeSerialize(inputString: string | Object): boolean;
declare function maybeBase64Decode(inputString: string, options?: WebPorridgeOptions): any;
declare function base64Encode(inputString: string): string;
declare function base64Decode(inputString: string): string;
declare function validateAction(action: string): void;
declare function isArray(inputData: any): boolean;
declare function isObject(inputData: any): boolean;
declare function isSerializableNumber(inputData: any): boolean;
export { base64Decode, base64Encode, isArray, isObject, isSerializableNumber, maybeBase64Decode, maybeDeserialize, maybeSerialize, validateAction };
