name: 'Run tests on Bun'

on:
  push:
    paths:
    - '.github/workflows/bun.yml'
    - 'src/**'
    - 'tests/**'
    - 'types/**'
    - 'package.json'
    - 'pnpm-lock.yaml'
    - 'vitest.config.ts'
  pull_request:
    paths:
    - '.github/workflows/bun.yml'
    - 'src/**'
    - 'tests/**'
    - 'types/**'
    - 'package.json'
    - 'pnpm-lock.yaml'
    - 'vitest.config.ts'
  workflow_dispatch:

jobs:
  default:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        fetch-depth: 10

    - uses: oven-sh/setup-bun@8f24390df009a496891208e5e36b8a1de1f45135 # v1.2.1
    - name: Install dependencies
      run: bun install --frozen-lockfile --strict-peer-dependencies

    - name: Install Playwright
      run: bun run playwright install --with-deps

    - name: Lint source
      run: bun run --if-present lint

    - name: Build source
      run: bun run --if-present build

    - name: Run tests
      run: bun run --if-present test
