name: "Run tests on Deno"

on:
  push:
    paths:
      - ".github/workflows/deno.yml"
      - "src/**"
      - "tests/**"
      - "types/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "vitest.config.ts"
  pull_request:
    paths:
      - ".github/workflows/deno.yml"
      - "src/**"
      - "tests/**"
      - "types/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "vitest.config.ts"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        deno-version: ["v2.0", "v2.1", "v2.2", "v2.3", "v2.4"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 8

      - uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}

      - uses: actions/cache@v4
        name: Set up dependency cache
        with:
          path: |
            ~/.cache/deno
            ~/.deno/bin
            ~/.deno/gen
            ~/.deno/deps
          key: ${{ runner.os }}-deno-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-deno-store-

      - name: Install npm dependencies
        run: deno install --allow-scripts=npm:msw@2.7.0,npm:esbuild@0.15.18

      - name: Install Playwright
        run: deno run --allow-all npm:playwright install --with-deps

      - name: Lint Source
        run: deno lint --rules-exclude=no-explicit-any --ignore=node_modules **/*.ts

      - name: Run Tests
        run: deno run --allow-all npm:vitest run
