name: "Run tests on NodeJS"

on:
  push:
    paths:
      - ".github/workflows/node.yml"
      - "src/**"
      - "tests/**"
      - "types/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "vitest.config.ts"
  pull_request:
    paths:
      - ".github/workflows/node.yml"
      - "src/**"
      - "tests/**"
      - "types/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "vitest.config.ts"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ["lts/*", "latest"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_store_path::$(pnpm store path)"

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_store_path }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --strict-peer-dependencies

      - name: Install Playwright
        run: pnpm dlx playwright install --with-deps

      - name: Lint source
        run: pnpm exec biome ci

      - name: Build source
        run: pnpm run --if-present build

      - name: Run tests
        run: pnpm run --if-present test
