name: 'Run tests on NodeJS'

on:
  push:
    paths:
    - '.github/workflows/node.yml'
    - 'src/**'
    - 'tests/**'
    - 'types/**'
    - 'package.json'
    - 'pnpm-lock.yaml'
    - 'vitest.config.ts'
  pull_request:
    paths:
    - '.github/workflows/node.yml'
    - 'src/**'
    - 'tests/**'
    - 'types/**'
    - 'package.json'
    - 'pnpm-lock.yaml'
    - 'vitest.config.ts'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ['lts/*', '*']

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        fetch-depth: 10

    - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
      with:
        node-version: ${{ matrix.node-version }}

    - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
      with:
        version: 10

    - name: Get pnpm store directory
      id: pnpm-cache
      run: |
        echo "::set-output name=pnpm_store_path::$(pnpm store path)"

    - uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.pnpm_store_path }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install --frozen-lockfile --strict-peer-dependencies

    - name: Install Playwright
      run: pnpm dlx playwright install --with-deps

    - name: Lint source
      run: pnpm run --if-present lint

    - name: Build source
      run: pnpm run --if-present build

    - name: Run tests
      run: pnpm run --if-present test
